### ISSUE TITLE
Manage Solution Extensions - Could not load type error

### ISSUE THREAD

**Issue by DonovanAGBR** [loop8ack/ExtensionPackTools#71] opened 2023-03-29 20:49 UTC
**Describe the bug**
When I try to "Manage Solution Extensions..." in Visual Studio Enterprise 2022 (64-bit) - Preview, Version 17.6.0 Preview 2.0 , Extension Manager 2022 Version: 1.1.82, I get this error message:

Extension Manager 2022
Could not load type 'Microsoft.VisualStudio.ExtensionManager.GalleryOnlineExtension' from assembly 'Microsoft.VisualStudio.ExtensionEngine, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."

**To Reproduce**
1. Open a solution
2. Right click on the solution 
3. Select "Manage Solution Extensions..."

**Expected behavior**
A modal window with a listing of installed extensions should appear.

**Screenshots**
![devenv_Xw7qGggHGn](https://user-images.githubusercontent.com/113369139/228660879-4becb254-7d9d-43d2-917c-3fdd234b40e6.png)

**Additional context**
I attempted to uninstall and reinstall the extension, but still received the error.

**Comment by robert-andrzejuk** [comment] 2023-04-06 11:24
Isn't this a duplicate of #70 ?

**Comment by loop8ack** [comment] 2023-05-14 14:08
I have described a fix for the problem here: https://github.com/madskristensen/ExtensionPackTools/issues/70#issuecomment-1546908590

**Comment by zackmuc** [comment] 2023-05-15 19:06
@loop8ack  Microsoft.VisualStudio.ExtensionEngineContract.dll is missing in my VS 17.5.5

**Comment by loop8ack** [comment] 2023-05-15 19:11
@zackmuc
Did the extension work for you before my update?
If yes, then the broken update came afterwards and has not been released yet.
However, I will need some time to look into it, so you should continue using the previous version until I have a fix.

**Comment by loop8ack** [comment] 2023-05-19 20:10
@zackmuc
I found a solution to the problem that the two versions (Normal and Preview) differ too much.
I took the repository from @madskristensen, I couldn't set up AppVeyor yet, so I attached a build for you.
Please test if it solves your problem, then I'll put an update online.

[Download: ExtensionManager2022.zip](https://github.com/loop8ack/ExtensionPackTools/files/11520153/ExtensionManager2022.zip)

**Comment by pbldk** [comment] 2023-05-24 17:08
Works here for me now.

**Comment by loop8ack** [comment] 2023-05-25 19:39
AppVeyor is live: https://ci.appveyor.com/project/loop8ack/extensionpacktools
An update for the Visual Studio Marketplace is also coming.

**Closed as completed** 2023-07-21 05:45 UTC
Labels: bug
