### ISSUE TITLE
Visual Studio 2022 17.8 displays an error dialog

### ISSUE THREAD

**Issue by xperiandri** [loop8ack/ExtensionPackTools#78] opened 2023-09-28 22:02 UTC
Preview 2.0
![image](https://github.com/loop8ack/ExtensionPackTools/assets/2365592/7756b3a9-fd7e-4155-80c2-5f43f987fa4c)

**Comment by thakyZ** [comment] 2023-10-23 14:31
I can confirm this happens on VS 2022 17.7.8
Here is a copy of the activity log:
https://gist.github.com/thakyZ/de572e9973fb8c555ffce53a4574c114

**Comment by karenpayneoregon** [comment] 2023-10-25 11:59
Also with 17.7.5

**Comment by Hefaistos68** [comment] 2023-11-16 09:17
Same on 17.8 release

**Comment by Thieum** [comment] 2023-11-22 13:52
Same on 17.8.1.

The extension will also prevent having multiple visual studio instances opened at the same time since 17.8.0. The second visual studio instance will just crash after a few seconds. Disabling the extension fixes the issue.

`<entry>
    <record>2752</record>
    <time>2023/11/22 13:49:25.061</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [ExtensionManagerPackage]Source: &apos;Microsoft.VisualStudio.Shell.Framework&apos; Description: .ctor must be called on the UI thread.&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8001010E): .ctor must be called on the UI thread.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)&#x000D;&#x000A;   at Community.VisualStudio.Toolkit.SolutionEvents..ctor()&#x000D;&#x000A;   at Community.VisualStudio.Toolkit.Events.get_SolutionEvents()&#x000D;&#x000A;   at ExtensionManager.ExtensionManagerPackage.&lt;HandleSolutionExtensionsAsync&gt;d__4.MoveNext() in C:\projects\extensionpacktools\src\ExtensionManager.Vsix.Shared\ExtensionManagerPackage.cs:line 83&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at ExtensionManager.ExtensionManagerPackage.&lt;InitializeAsync&gt;d__2.MoveNext() in C:\projects\extensionpacktools\src\ExtensionManager.Vsix.Shared\ExtensionManagerPackage.cs:line 56&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{3EC2FA73-1F0D-4E31-88C3-604C4E46EC14}</guid>
    <hr>0x8001010e</hr>
    <errorinfo></errorinfo>
  </entry>`

**Comment by wernervn** [comment] 2023-12-04 06:48
Also getting it on v17.9 preview 1.1. When I open VS on its own and then a solution from the MRU menu, I get the dialog shown by OP.

If I open VS by selecting a project from the VS jump list, then VS just hangs. I've had to uninstall this extension because it has mad VS unusable for me, as I mostly open VS using the jump list.

Getting this after the most recent update.

**Comment by loop8ack** [comment] 2023-12-06 21:50
I have just uploaded a new version, please test to see if the errors still occur.

@Thieum 

The ActivityLog Entry you provided matches my [Redevelopment](https://github.com/loop8ack/ExtensionPackTools/tree/Redevelopment) of the extension, which is not yet live. Could it be that you have been using the AppVeyor build and thus, unknowingly, my redevelopment?

You can find the build with the fixes here: [AppVeyor Redevelopment](https://ci.appveyor.com/project/loop8ack/extensionpacktools/builds/48774612/artifacts)

Please test to see if the errors have been resolved and everything works again.
Did you have any other problems with this version? The redevelopment is not live yet, as I still need to do more testing, so I appreciate any feedback.

**Comment by Mike-E-angelo** [comment] 2023-12-22 09:25
FWIW I was getting the reported error and uninstalled+reinstalled and am able to use this extension as expected. 🙏

**Comment by loop8ack** [comment] 2023-12-28 16:18
Since I'm not getting any more answers here, I'll close this.

**Closed as completed by loop8ack** 2023-12-28 16:18 UTC
